name: Infracost Workflow
on:
  workflow_call:
    inputs:
      # working-directory is added to specify "terraform" directory in project source code as that's where the terraform files live.
      working-directory:
        required: true
        type: string
        default: 'main'
      # terraform tfvars
      tfvars:
        required: true
        type: string
      # infracost usage file path
      usage-file:
        required: false
        type: string
        default: ''

jobs:
  infracost:
    name: Infracost Analysis
    runs-on: ubuntu-latest
    env:
      TF_ROOT: ${{ inputs.working-directory }}
      TF_VARS_LOCATION: $
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Generate Infracost Estimate Baseline
        run: |
          cd ${TF_ROOT}
          echo ${{ inputs.tfvars }} > /tmp/terraform.tfvars
          infracost breakdown --path=. \
                              --terraform-var-file=/tmp/terraform.tfvars \
                              --usage-file=${{ inputs.usage-file }} \
                              --format=json \
                              --out-file=/tmp/infracost_base.json
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Infracost Diff
        run: |
          cd ${TF_ROOT}
          echo ${{ inputs.tfvars }} > /tmp/terraform.tfvars
          infracost diff --path=. \
                        --format=json \
                        --terraform-var-file=/tmp/terraform.tfvars \
                        --usage-file=${{ inputs.usage-file }} \
                        --compare-to=/tmp/infracost_base.json \
                        --out-file=/tmp/infracost.json
      - name: Infracost Comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=${{ github.token }} \
                                  --pull-request=${{ github.event.pull_request.number }} \
                                  --behavior=update
