name: Infracost Workflow
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  infracost_master:
    name: Infracost
    if: github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_ROOT: main
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Generate Infracost Cost Estimate Baseline
        run: |
          infracost breakdown --path=$TF_ROOT \
                              --format=json \
                              --out-file=/tmp/infracost_base.json
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Infracost Diff
        run: |
          infracost diff --path=$TF_ROOT \
                        --format=json \
                        --compare-to=/tmp/infracost_base.json \
                        --out-file=/tmp/infracost.json
      - name: Infracost Comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=#{{ github.token }} \
                                  --pull-request=${{ github.event.pull_request.number }} \
                                  --behavior=update
