name: 'Infracost Analysis'
on:
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  infracost:
    permissions:
      contents: write
      pull-requests: write
    if: github.event.pull_request.base.ref == 'master'
    uses: safderun/personal_infra/.github/workflows/infracost-action.yml@dev
    with:
      working-directory: ./main
      usage-file: ./infracost-usage.yml
      tfvars: TFVARS_MAIN
