name: Infracost Workflow
on:
  workflow_call:
    inputs:
      # working-directory is added to specify "terraform" directory in project source code as that's where the terraform files live.
      working-directory:
        required: true
        type: string
        default: '.'
      # infracost usage file path
      config-file-path:
        required: false
        type: string
        default: 'infracost.yml'

jobs:
  infracost:
    name: Infracost Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      TF_ROOT: ${{ inputs.working-directory }}
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Generate Infracost Estimate Baseline
        run: |
          cd ${TF_ROOT}
          infracost breakdown --path=. \
                              --format=json \
                              --config-file=${{ inputs.config-file-path }} \
                              --out-file=/tmp/infracost_base.json
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate Infracost Diff
        run: |
          cd ${TF_ROOT}
          infracost diff --path=. \
                        --format=json \
                        --config-file=${{ inputs.config-file-path }} \
                        --compare-to=/tmp/infracost_base.json \
                        --out-file=/tmp/infracost.json
      - name: Infracost Comment
        run: |
          infracost comment github --path=/tmp/infracost.json \
                                  --repo=$GITHUB_REPOSITORY \
                                  --github-token=${{ github.token }} \
                                  --pull-request=${{ github.event.pull_request.number }} \
                                  --behavior=hide-and-new
